language: java
jdk:
    - openjdk8
    - oraclejdk8
    - oraclejdk11
    - openjdk11
dist: bionic
services:
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE KJudge_DB;'
after_script:
    - mysql -e 'DROP DATABASE KJudge_DB;'
install: mvn clean install -D skipTests
script: mvn test -pl KJudge-data
notifications:
    email:
        recipients:
            - subhadrasundar@gmail.com
            - sschakraborty@hotmail.com
        on_success: always
        on_failure: always